# [[redirects]]
#   from = "https://io-oi.netlify.com/*"
#   to = "https://io-oi.me/:splat"
#   force = true

# [[headers]]
#   for = "/*"
#   [headers.values]
# 	Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
#   Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net hayschan.netlify.app; frame-ancestors 'none'; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net; script-src 'self' 'unsafe-inline' 'unsafe-eval' static.cloudflareinsights.com ajax.cloudflare.com unpkg.com/artitalk  cdn.jsdelivr.net https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com https://www.autohan.org; connect-src 'self' cloudflareinsights.com app-router.com 3kaiwrbk.api.lncldglobal.com https://www.google-analytics.com; img-src 'self' img.shields.io cdn.jsdelivr.net hayschan.netlify.app https://www.google-analytics.com https://*.loli.net; frame-src www.youtube-nocookie.com youtube-nocookie.com www.youtube.com youtube.com; report-uri https://haysc.report-uri.com/r/d/csp/enforce"
#   X-Frame-Options = "SAMEORIGIN"
#   Referrer-Policy = "no-referrer-when-downgrade"
#   # Permissions-Policy = "accelerometer=(none); camera=(none); gyroscope=(none); magnetometer=(none); microphone=(none); payment=(none); usb=(none)"
#   # Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; camera 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
#   Permissions-Policy = '''
#             accelerometer=(),
#             ambient-light-sensor=(),
#             autoplay=(self),
#             camera=(),
#             encrypted-media=(),
#             fullscreen=(self),
#             geolocation=(),
#             gyroscope=(),
#             magnetometer=(),
#             microphone=(),
#             midi=(),
#             payment=(),
#             picture-in-picture=(self),
#             usb=(),
#             vibrate=(),
#             vr=()
#         '''
#   X-XSS-Protection = "1; mode=block"